---
AWSTemplateFormatVersion: "2010-09-09"
Stack: "RHStack"
Resources:
  RHLambdaCognitoSignUpRole:
    Type: "AWS::IAM::Role"
    RoleName: !Join [ "", [ !Ref "AWS::StackEnv", RHLambdaCognitoSignUpRole ] ]
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - "sts:AssumeRole"
      Policies:
        -
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              Action: "cognito-idp:SignUp"
              Effect: Allow
              Resource: "*"
          PolicyName: RHCognitoSignUp
  DevRHSignUpLambda:
    Type: "AWS::Lambda::Function"
    DependsOn:
      - RHLambdaCognitoSignUpRole
    Properties:
      FunctionName: !Join [ "-", [ !Ref "AWS::StackEnv", rh-sign-up-lambda ] ]
      Role:
        "Fn::GetAtt":
          - RHLambdaCognitoSignUpRole
          - Arn
      Code:
        S3Bucket: rh-configuration-resources
        S3Key: lambdas/rh-cognito-sign-up.zip
      Handler: index.handler
      MemorySize: 128
      Runtime: nodejs6.10
      Timeout: 10
      Environment:
        Variables:
          CLIENT_ID: 14idvaikjll479k7vg5g0vp99
